### ISSUE TITLE
Investigate byte pair encoding for less error-prone sequence classification.

### ISSUE THREAD

**Issue by rhpvorderman** [rhpvorderman/sequali#99]
Credit @luukromeijn

**Comment by rhpvorderman** [comment]
Current methodology with Sequence Identity using a smith-waterman alignment gives the most acurate result. One problem is reducing the number of candidates using kmers. Current methodology is still a bit slow.

**Comment by luukromeijn** [comment]
Sadly, in my experience, BPE encoding is not faster than using k-mers. Even though this depends on what settings you use for both algorithms (k/vocab_size for k-mer/BPE). BPE has a better accuracy/speed trade-off tho. But for this purpose, it seems like using k-mers is better.

**Comment by rhpvorderman** [comment]
k-mers is also very simple to implement. So I will go with that for candidate selection then. Thank you for reporting back!
